---
Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-1a
      ImageId: ami-a4c7edb2
      InstanceType: t2.micro
      SecurityGroups:
        - !Ref ServerSecurityGroup
      UserData:
        Fn::Base64: |
           #!/bin/bash
           sudo su
           yum update -y
           yum install java
           yum install wget
           cd /root
           wget https://download.elastic.co/elasticsearch/elasticsearch/elasticsearch-1.7.2.noarch.rpm
           yum install elasticsearch-1.7.2.noarch.rpm -y
           rm -f elasticsearch-1.7.2.noarch.rpm
           cd /usr/share/elasticsearch/
           ./bin/plugin -install mobz/elasticsearch-head
           ./bin/plugin -install lukas-vlcek/bigdesk
           ./bin/plugin install elasticsearch/elasticsearch-cloud-aws/2.7.1
           ./bin/plugin --install lmenezes/elasticsearch-kopf/1.5.7
           service elasticsearch start

  ServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: allow connections from specified CIDR ranges
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 443
        ToPort: 443
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 9200
        ToPort: 9200
        CidrIp: 0.0.0.0/0
